### ISSUE TITLE
No compatible version found: angular2-universal-preview@0.80.0

### ISSUE THREAD

**Issue by PierrickLozach** [pmachowski/angular2-starter-kit#1]
I get this error when I run `npm install`:

```
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Pierrick\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "angular2-universal-preview"
npm ERR! node v5.8.0
npm ERR! npm  v3.8.1

npm ERR! No compatible version found: angular2-universal-preview@0.80.0
npm ERR! Valid install targets:
npm ERR! 0.70.8, 0.70.7, 0.70.6, 0.70.5, 0.70.4, 0.70.3, 0.70.2, 0.70.1, 0.70.0, 0.61.2, 0.61.1, 0.61.0, 0.60.2, 0.60.1, 0.60.0, 0.55.4, 0.55.3, 0.55.2, 0.55.1, 0.55.0, 0.52.0, 0.51.0, 0.50.0, 0.42.0, 0.41.2, 0.41.1, 0.41.0, 0.40.0, 0.32.2, 0.32.1, 0.32.0, 0.31.0, 0.30.1, 0.30.0, 0.29.0, 0.28.0, 0.27.0, 0.26.0, 0.25.0, 0.24.0, 0.23.1, 0.23.0, 0.22.1, 0.22.0, 0.21.0, 0.20.0, 0.19.0, 0.18.0, 0.17.0, 0.16.0, 0.14.0, 0.13.0, 0.12.1, 0.12.0, 0.11.0, 0.10.0, 0.9.0, 0.8.1, 0.8.0, 0.6.1, 0.6.0, 0.5.4, 0.5.3, 0.5.2, 0.5.1, 0.5.0, 0.4.7, 0.4.6, 0.4.4, 0.4.3, 0.4.2, 0.4.1, 0.4.0, 0.3.7, 0.3.6, 0.3.5, 0.3.4, 0.3.2, 0.3.1, 0.3.0, 0.2.0, 0.1.9, 0.1.8, 0.1.7, 0.1.6, 0.1.5, 0.1.3, 0.1.2, 0.1.1, 0.1.0
```

**Comment by aalbericio** [comment]
Same here. Changing the angular2-universal version to 0.70.8 (latest) did the trick.

**Comment by emretoprak** [comment]
change `"angular2-universal-preview": "0.80.0",`  to `"angular2-universal-preview": "0.70.8",` in package.json

**Comment by PierrickLozach** [comment]
That fixed it. Got other issues but at least this one can be closed.

**Comment by aalbericio** [comment]
There is also an issue when running npm install on windows machines:

"postinstall": "if test \"$NODE_ENV\" != \"production\" ; then typings install && npm run webdriver:update ; fi"

I got the whole things installing and building by removing the if statement and leaving the remaining code:

typings install && npm run webdriver:update ;

Anyway, I get the feeling that script needs some review for windows machines.

**Comment by peter-mach** [comment]
I have fixed this issue. @emretoprak next time don't hesitate to submit Pull Request ;)

@aalbericio thanks for letting me know about windows issues. I'm on a mac but I will get it reviewed on Windows.
