### ISSUE TITLE
Favicon doesn't work

### ISSUE THREAD

**Issue by mazhuravlev** [pmachowski/angular2-starter-kit#10]
Favicon is imported by require in [src/server/index.html#L7](https://github.com/pmachowski/angular2-starter-kit/blob/master/src/server/index.html#L7).

Here is request url in browser, note the trailing **)'**:
`Request URL:http://localhost:3000/assets/images/favicon.ico')`

This causes server to respond with entire page.

**Comment by mazhuravlev** [comment]
I changed it to this,
`<link rel="icon" type="image/x-icon" href="/assets/images/favicon.ico">`

**Comment by peter-mach** [comment]
Good catch @mazhuravlev 👍 

I've fixed this in the latest commit #310b6b16a56659fb0bd6c893fcbd820301da0224
