### ISSUE TITLE
Uncaught TypeError: Cannot read property 'cleanup' of null

### ISSUE THREAD

**Issue by netlander** [pmachowski/angular2-starter-kit#11]
Getting the following error in browser console:
`Uncaught TypeError: Cannot read property 'cleanup' of null (index):675`

Not sure if related but also getting some deprecation warnings from Webpack:
`DEPRECATION WARNING:`renderToStringWithPreboot`is no longer supported and will be removed in next release.`
`DEPRECATION WARNING:`renderToString`is no longer supported and will be removed in next release.`

**Comment by peter-mach** [comment]
Hi @netlander. Thank you for using my starter 👍 

I'm aware of this warnings and I'll be fixing them in this weekend.

**Comment by peter-mach** [comment]
Closing, fixed by @paullryan
