### ISSUE TITLE
Server Error when npm run serve

### ISSUE THREAD

**Issue by netlander** [pmachowski/angular2-starter-kit#12]
Getting this `Error: Server Error` with following stack trace when running production mode i.e. `npm run serve`. Below I have also included the browser console output.

`
Error: Server Error
    at E:\0000.src\02.web.02\00.webpack\angular2-starter-kit-master\dist\private\server.js:83:23
    at Layer.handle_error (E:\0000.src\02.web.02\00.webpack\angular2-starter-kit-master\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (E:\0000.src\02.web.02\00.webpack\angular2-starter-kit-master\node_modules\express\lib\router\index.js:310:13)
    at E:\0000.src\02.web.02\00.webpack\angular2-starter-kit-master\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (E:\0000.src\02.web.02\00.webpack\angular2-starter-kit-master\node_modules\express\lib\router\index.js:330:12)
    at next (E:\0000.src\02.web.02\00.webpack\angular2-starter-kit-master\node_modules\express\lib\router\index.js:271:10)
    at E:\0000.src\02.web.02\00.webpack\angular2-starter-kit-master\dist\private\server.js:69:13
    at Layer.handle [as handle_request] (E:\0000.src\02.web.02\00.webpack\angular2-starter-kit-master\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (E:\0000.src\02.web.02\00.webpack\angular2-starter-kit-master\node_modules\express\lib\router\index.js:312:13)
    at E:\0000.src\02.web.02\00.webpack\angular2-starter-kit-master\node_modules\express\lib\router\index.js:280:7
DEPRECATION WARNING:`renderToStringWithPreboot`is no longer supported and will be removed in next release.
DEPRECATION WARNING:`renderToString`is no longer supported and will be removed in next release.
DEPRECATION WARNING:`renderToStringWithPreboot`is no longer supported and will be removed in next release.
DEPRECATION WARNING:`renderToString`is no longer supported and will be removed in next release.
`

Browser console output:
`
dom_adapter.ts:143POST http://localhost:3000/sockjs-node/464/f41f5cug/xhr_streaming?t=1461350744960 500 (Internal Server Error)scheduleTask @ dom_adapter.ts:143ZoneDelegate.scheduleTask @ dom_adapter.ts:143Zone.scheduleMacroTask @ dom_adapter.ts:143(anonymous function) @ dom_adapter.ts:143send @ VM1625:3AbstractXHRObject._start @ abstract-xhr.js:128(anonymous function) @ abstract-xhr.js:21ZoneDelegate.invokeTask @ dom_adapter.ts:143Zone.runTask @ dom_adapter.ts:143ZoneTask.invoke @ dom_adapter.ts:143
(index):1 EventSource's response has a MIME type ("text/html") that is not "text/event-stream". Aborting the connection.
3VM1784 worker.js:10Uncaught reflect-metadata shim is required when using class decorators(anonymous function) @ VM1784 worker.js:10(anonymous function) @ VM1784 worker.js:10__webpack_require__ @ VM1784 worker.js:1(anonymous function) @ VM1784 worker.js:9__webpack_require__ @ VM1784 worker.js:1(anonymous function) @ VM1784 worker.js:1__webpack_require__ @ VM1784 worker.js:1(anonymous function) @ VM1784 worker.js:10__webpack_require__ @ VM1784 worker.js:1(anonymous function) @ VM1784 worker.js:6__webpack_require__ @ VM1784 worker.js:1(anonymous function) @ VM1784 worker.js:1__webpack_require__ @ VM1784 worker.js:1(anonymous function) @ VM1784 worker.js:23__webpack_require__ @ VM1784 worker.js:1(anonymous function) @ VM1784 worker.js:1__webpack_require__ @ VM1784 worker.js:1(anonymous function) @ VM1784 worker.js:1(anonymous function) @ VM1784 worker.js:1
websocket.js:32 WebSocket connection to 'ws://localhost:3000/sockjs-node/464/xc03qg3h/websocket' failed: Connection closed before receiving a handshake response
dom_adapter.ts:143POST http://localhost:3000/sockjs-node/464/ilyvw4dg/xhr?t=1461350747181 500 (Internal Server Error)scheduleTask @ dom_adapter.ts:143ZoneDelegate.scheduleTask @ dom_adapter.ts:143Zone.scheduleMacroTask @ dom_adapter.ts:143(anonymous function) @ dom_adapter.ts:143send @ VM1625:3AbstractXHRObject._start @ abstract-xhr.js:128(anonymous function) @ abstract-xhr.js:21ZoneDelegate.invokeTask @ dom_adapter.ts:143Zone.runTask @ dom_adapter.ts:143ZoneTask.invoke @ dom_adapter.ts:143
jsonp?c=_jp.alntfjc:1 Uncaught SyntaxError: Unexpected token <
client:70 [WDS] Disconnected!sock.onclose @ client:70EventTarget.dispatchEvent @ eventtarget.js:49(anonymous function) @ main.js:356ZoneDelegate.invokeTask @ dom_adapter.ts:143Zone.runTask @ dom_adapter.ts:143ZoneTask.invoke @ dom_adapter.ts:143
VM1784 worker.js:10Uncaught reflect-metadata shim is required when using class decorators(anonymous function) @ VM1784 worker.js:10(anonymous function) @ VM1784 worker.js:10__webpack_require__ @ VM1784 worker.js:1(anonymous function) @ VM1784 worker.js:9__webpack_require__ @ VM1784 worker.js:1(anonymous function) @ VM1784 worker.js:1__webpack_require__ @ VM1784 worker.js:1(anonymous function) @ VM1784 worker.js:10__webpack_require__ @ VM1784 worker.js:1(anonymous function) @ VM1784 worker.js:6__webpack_require__ @ VM1784 worker.js:1(anonymous function) @ VM1784 worker.js:1__webpack_require__ @ VM1784 worker.js:1(anonymous function) @ VM1784 worker.js:23__webpack_require__ @ VM1784 worker.js:1(anonymous function) @ VM1784 worker.js:1__webpack_require__ @ VM1784 worker.js:1(anonymous function) @ VM1784 worker.js:1(anonymous function) @ VM1784 worker.js:1
dom_adapter.ts:143 POST http://localhost:3000/sockjs-node/689/qcqbzzg5/xhr_streaming?t=1461350750402 500 (Internal Server Error)scheduleTask @ dom_adapter.ts:143ZoneDelegate.scheduleTask @ dom_adapter.ts:143Zone.scheduleMacroTask @ dom_adapter.ts:143(anonymous function) @ dom_adapter.ts:143send @ VM1625:3AbstractXHRObject._start @ abstract-xhr.js:128(anonymous function) @ abstract-xhr.js:21ZoneDelegate.invokeTask @ dom_adapter.ts:143Zone.runTask @ dom_adapter.ts:143ZoneTask.invoke @ dom_adapter.ts:143
(index):1 EventSource's response has a MIME type ("text/html") that is not "text/event-stream". Aborting the connection.
`

**Comment by peter-mach** [comment]
Will look into that. Thanks for reporting

**Comment by netlander** [comment]
Sorry, missed the `npm run build` step. After executing it the production mode runs without any errors.
Closing the issue and adding a star.

**Comment by peter-mach** [comment]
I'm glad that it works for you and thanks for the star :)
