### ISSUE TITLE
Component styles are not included in server-side rendering

### ISSUE THREAD

**Issue by mazhuravlev** [pmachowski/angular2-starter-kit#15]
Styles defined in @Component as text or require call are not rendered on server.
They appear when Angular is started.

**Comment by peter-mach** [comment]
@mazhuravlev thanks for taking the time to report this 👍  I will look into it.

**Comment by mazhuravlev** [comment]
When there are styles in component, style scope attributes are added in server-side rendering:
`<div _ngcontent-muq-7="" class="item">item</div>`
With no styles, they aren't:
`<div class="item">item</div>`
It all happens with JavaScript disabled in browser.

**Comment by peter-mach** [comment]
Fixed in v.2.0.0
