### ISSUE TITLE
Renders <html> headers twice

### ISSUE THREAD

**Issue by riwarren** [pmachowski/angular2-starter-kit#18]
Below is a snippet of the page source. This is a fresh checkout from the latest repo here on github:

```
<!DOCTYPE html>
<html>
  <head>
    <title>Angular 2 Starter Kit - Uniwersal, Webpack, PostCSS, Node.js/Express</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/x-icon" href="assets/images/favicon.ico">
    <base href="/"></base>
    <link rel="stylesheet" href="/styles.css" media="screen" charset="utf-8">
  </head>
  <body>
    <!DOCTYPE html><html><head>
    <title>Angular 2 Starter Kit - Uniwersal, Webpack, PostCSS, Node.js/Express</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/x-icon" href="assets/images/favicon.ico">
    <base href="/">
    <link rel="stylesheet" href="/styles.css" media="screen" charset="utf-8">
  </head>
  <body>
    <app><router-outlet></router-outlet>
```

Why is it doing this?  and how do I make it stop?

**Comment by mazhuravlev** [comment]
What is your node version and how exactly do you start the application?

**Comment by riwarren** [comment]
I have tried with node versions:  4.5.0, 5.9.0 and 6.2.3 I believe? Same
result with all of them.

I start it with

npm run build
npm run serve:pm2

I spent all day yesterday trying to get that other angular2 universal kit
on github that yours is based off of to work but encountered nothing but
dep conflicts and issues with typings.

Then I found yours and it works right put of the box (and is structured far
better), but can't seem to figure out why it's rendering the head content
twice. I'm going crazy trying to figure this out, haha.

**Comment by mazhuravlev** [comment]
I have launched it now, same problem. You can checkout more recent release and try it again, to figure out if it was always like this.

**Comment by riwarren** [comment]
I am assuming you mean an older release?

**Comment by riwarren** [comment]
Which release if your website using? The one is the same as the example in
the git repository. It doesn't have this problem.

**Comment by riwarren** [comment]
So it works on the 1.3.1 release. Except server side scripting isnt working
right. It injects a big section of obfuscated javascript into the page
instead of the page elements.

I noticed your website does this too. Whats with that? SSR should display
all the page elements, not inject javascript into the page...

**Comment by peter-mach** [comment]
Fixed in v.2.0.0
