### ISSUE TITLE
Fix node scripts for windows users

### ISSUE THREAD

**Issue by aalbericio** [pmachowski/angular2-starter-kit#2]
There are some issues when running node scripts on Windows machines, mainly related to ENV variables being used: NODE_ENV, etc

Affected tasks: install, build, etc

Thank you.

**Comment by peter-mach** [comment]
Thanks for letting me know @aalbericio I'm mainly on mac but I will look into it on windows machine.

**Comment by peter-mach** [comment]
@aalbericio the windows build issues are now fixed

**Comment by aalbericio** [comment]
It works. Thanks a lot.
