### ISSUE TITLE
One component for all?

### ISSUE THREAD

**Issue by aralroca** [pmachowski/angular2-starter-kit#3]
Why are you creating only one component "home" with all the content inside? this is not the grace of components!

**Comment by peter-mach** [comment]
It's temporary solution. I will do the componentization soon.

**Comment by aralroca** [comment]
Okey! :+1:  By the way: Good job!

**Comment by peter-mach** [comment]
@aralroca Thanks for using this starter You rock :100:  
I've divided the homepage into functional components. You can pull to get latest changes.
Best, Peter.
