### ISSUE TITLE
http/2

### ISSUE THREAD

**Issue by bkinsey808** [pmachowski/angular2-starter-kit#7]
Support for http/2 would be an interesting and forward-thinking feature for this project.

**Comment by paullryan** [comment]
Given that this starter uses express.js for it's server side routing, to support http/2 it would have to wait till https://github.com/molnarg/node-http2/issues/100 is addressed which requires https://github.com/expressjs/express/issues/2432 from the express team (slated for express 5.0). 

If you want/need support for http2/spdy today you can switch the routing your self in server.js to another engine such as Koa and use either the node-spdy or node-http2 modules in serve.js yourself. Seems to be working for me.

**Comment by bkinsey808** [comment]
Thanks for the info. Appreciate it.
